{
	"deprecated": false,
	"cpeName": "cpe:2.3:a:redhat:ansible_engine:2.8.9:*:*:*:*:*:*:*",
	"cpeNameId": "786E3E94-585A-49FC-9DCD-9604BB59B418",
	"created": "2020-04-01T17:27:30.290",
	"lastModified": "2020-04-01T17:27:30.290",
	"titles": [
		{
			"title": "Red Hat Ansible Engine 2.8.9",
			"lang": "en"
		}
	],
	"refs": [
		{
			"ref": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1737",
			"type": "Advisory"
		}
	]
}
