{
	"deprecated": false,
	"cpeName": "cpe:2.3:a:ibm:planning_analytics_local:2.0.0:*:*:*:*:*:*:*",
	"cpeNameId": "897DA49F-EE46-4D18-A451-C066687FF0A4",
	"created": "2019-10-03T13:42:48.237",
	"lastModified": "2019-10-03T13:42:48.237",
	"titles": [
		{
			"title": "IBM Planning Analytics Local 2.0.0",
			"lang": "en"
		}
	],
	"refs": [
		{
			"ref": "https://www.ibm.com/mysupport/s/topic/0TO500000002PWWGA2/planning-analytics-local?language=en_US&productId=01t50000004Xdyn",
			"type": "Product"
		},
		{
			"ref": "https://exchange.xforce.ibmcloud.com/vulnerabilities/145118",
			"type": "Advisory"
		}
	]
}
