{
	"deprecated": false,
	"cpeName": "cpe:2.3:a:nic:knot_resolver:5.5.1:*:*:*:*:*:*:*",
	"cpeNameId": "4119F372-6AE4-4A5F-9142-BA0FFBE50793",
	"created": "2022-06-27T16:30:22.713",
	"lastModified": "2022-11-09T15:10:25.333",
	"titles": [
		{
			"title": "Nic Knot Resolver 5.5.1",
			"lang": "en"
		}
	],
	"refs": [
		{
			"ref": "https://exchange.xforce.ibmcloud.com/vulnerabilities/229244",
			"type": "Advisory"
		},
		{
			"ref": "https://github.com/CZ-NIC/knot-resolver",
			"type": "Version"
		},
		{
			"ref": "https://www.nic.cz/",
			"type": "Vendor"
		}
	]
}
