{
	"deprecated": false,
	"cpeName": "cpe:2.3:a:ibm:cognos_analytics:11.0.13:fixpack3:*:*:*:*:*:*",
	"cpeNameId": "2586DF85-1526-4A1E-8982-15E23A875440",
	"created": "2020-03-17T12:28:57.957",
	"lastModified": "2020-03-17T12:28:57.957",
	"titles": [
		{
			"title": "IBM Cognos Analytics 11.0.13 Fix Pack 3",
			"lang": "en"
		}
	],
	"refs": [
		{
			"ref": "https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=Cognos&product=ibm/Information+Management/Cognos+Analytics&release=11.0.13&platform=All&function=all",
			"type": "Version"
		}
	]
}
