{
  "deprecated": false,
  "cpeName": "cpe:2.3:a:ibm:cognos_analytics:11.0.13:fixpack1:*:*:*:*:*:*",
  "cpeNameId": "91A41997-120F-43FC-9753-E6963A337D25",
  "created": "2020-03-17T12:28:57.770",
  "lastModified": "2020-03-17T12:28:57.770",
  "titles": [
    {
      "title": "IBM Cognos Analytics 11.0.13 Fix Pack 1",
      "lang": "en"
    }
  ],
  "refs": [
    {
      "ref": "https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=Cognos&product=ibm/Information+Management/Cognos+Analytics&release=11.0.13&platform=All&function=all",
      "type": "Version"
    }
  ]
}
