{
	"deprecated": false,
	"cpeName": "cpe:2.3:a:ibm:cloud_pak_for_data:2.5:*:*:*:*:*:*:*",
	"cpeNameId": "D03ADE19-772D-45F8-9CF0-3C1602B91A1B",
	"created": "2023-12-16T03:42:31.200",
	"lastModified": "2023-12-16T03:42:31.200",
	"titles": [
		{
			"title": "IBM Cloud Pak For Data 2.5",
			"lang": "en"
		}
	],
	"refs": [
		{
			"ref": "https://exchange.xforce.ibmcloud.com/vulnerabilities/209575",
			"type": "Advisory"
		},
		{
			"ref": "https://www.ibm.com/support/pages/node/6490435",
			"type": "Advisory"
		}
	]
}
